### ISSUE TITLE
min and max params are not used in any way

### ISSUE THREAD

**Issue by dy** [lukem512/normalize-svg-path#4]
Passing them to options changes nothing.

Moreover, I'd go for making it a `range` option, to normalize to an output box, not some linear `min-max` range.

Also prob it is a good idea if `viewBox` is not defined to detect it automatically from svg commands range. Are there commands where the resulting path is outside of arguments bounds?

**Comment by dy** [comment]
Ah, there is https://github.com/lukem512/extract-svg-viewbox. @lukem512 what do you think if using it to detect `viewBox` if it is undefined?

**Comment by lukem512** [comment]
I'm not sure that package will help unless the entire SVG string is provided; it's really just a regex to extract the `viewBox` from that rather than computing it from the path data. One problem with trying to estimate it is that it the space around the SVG will not be preserved and that the`viewBox` might even be used to deliberately obscure parts of the image.

I agree that the the `min` and `max` range needs to be considered however! Do you mean that the `range` should specify both dimensions?

**Comment by lukem512** [comment]
See de799a0d2c6afd30a22daf45f426abaa2c1658f9

**Comment by dy** [comment]
@lukem512 yeah, that should make `min` and `max` params useful.

**Comment by dy** [comment]
https://github.com/icons8/svg-path-bounding-box is prob of use
